services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
