import { Action, ErrorComponent, IResourceItem, Refine } from '@refinedev/core'
import { RefineKbar, RefineKbarProvider } from '@refinedev/kbar'
import routerBindings, { DocumentTitleHandler, NavigateToResource, UnsavedChangesNotifier } from '@refinedev/react-router-v6'
import dataProvider from '@refinedev/simple-rest'
import { BarChart, Calendar, CirclePlay, Code, Download, Play, TvMinimalPlay } from 'lucide-react'
import { BrowserRouter, Outlet, Route, Routes } from 'react-router-dom'

import './App.css'
import { Layout, MenuItemProps } from './components/layout'
import { EventCalendar } from './pages/Calendar'
import { VideoPlayer } from './pages/VideoPlayer'
import { AnimationCreate, AnimationEdit, AnimationList } from './pages/animation'

const customTitleHandler = ({
	resource,
	action,
	params,
	pathname,
	autoGeneratedTitle
}: {
	resource?: IResourceItem
	action?: Action
	params?: Record<string, string | undefined>
	pathname?: string
	autoGeneratedTitle: string
}) => {
	return autoGeneratedTitle.replace('| Refine', '| 火拳')
}

function App() {
	const menuItems: MenuItemProps[] = [
		{
			icon: Calendar,
			label: '项目日历',
			path: '/calendar'
		},
		{
			icon: Code,
			label: '代码库',
			children: [
				{
					icon: Play,
					label: '运行代码',
					path: '/run-code'
				},
				{
					icon: Download,
					label: '下载源码',
					path: '/download-code'
				}
			]
		},
		{
			icon: BarChart,
			label: '数据分析',
			path: '/analytics'
		},
		{
			icon: TvMinimalPlay,
			label: '动画',
			path: '/animation'
		},
		{
			icon: CirclePlay,
			label: '播放器',
			path: '/player'
		}
	]

	return (
		<BrowserRouter>
			<RefineKbarProvider>
				<Refine
					dataProvider={dataProvider('http://localhost:3000/api/v1')}
					routerProvider={routerBindings}
					resources={[
						{
							name: 'calendar',
							list: '/calendar'
						},
						{
							name: 'animation',
							list: '/animation',
							create: '/animation/create',
							edit: '/animation/edit/:id'
						}
					]}
					options={{
						syncWithLocation: true,
						warnWhenUnsavedChanges: true,
						useNewQueryKeys: true,
						projectId: 'PLCq13-4rLMl1-olLWNJ'
					}}
				>
					<Routes>
						<Route
							element={
								<Layout menuItems={menuItems} title="Lysander">
									<Outlet />
								</Layout>
							}
						>
							<Route index element={<NavigateToResource resource="calendar" />} />
							<Route path="/calendar">
								<Route index element={<EventCalendar />} />
							</Route>

							<Route path="/animation">
								<Route index element={<AnimationList />} />
								<Route path="create" element={<AnimationCreate />} />
								<Route path="edit/:id" element={<AnimationEdit />} />
							</Route>

							<Route path="*" element={<ErrorComponent />} />
						</Route>

						<Route path="/player">
							<Route index element={<VideoPlayer />} />
						</Route>
					</Routes>

					<RefineKbar />
					<UnsavedChangesNotifier />
					<DocumentTitleHandler handler={customTitleHandler} />
				</Refine>
			</RefineKbarProvider>
		</BrowserRouter>
	)
}

export default App
